/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'christo' at '05/08/16 15:08' with Gradle 2.14.1
 *
 * @author christo, @date 05/08/16 15:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
